name: Adhoc main job

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - test
          - prod
        description : deployment environment
      space:
          type: choice
          options:
            - feature
            - qa
            - synthetic
            - actual
            - release
          description: space
          required: true
      deploy:
          type: boolean
          description: deploy a workflow
          default: true
      query:
          type: string
          description : sql queries to be executed ( multiple values are separated by | )


permissions:
      id-token: write
      contents: read

jobs:
    ci-deploy-and-launch:
      uses: ./.github/workflows/ad_hoc_launch_workflow.yml
      with:
        environment: ${{ inputs.environment }}
        space: ${{ inputs.space }}
        deploy: ${{ inputs.deploy }}
        skip_test: ${{ inputs.skip_test }}
        query: ${{ inputs.query }}
      secrets: inherit



