name: "Release"
on:
  workflow_call:

concurrency:
  group: release

jobs:
  release-solution:
    name: Release solution
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
    steps:
        - name: checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Generate Token
          id: generate-token
          uses: actions/create-github-app-token@v1
          with:
              app-id: ${{ secrets.GH_RELEASE_APP_ID }}
              private-key : ${{ secrets.GH_RELEASE_PRIVATE_KEY }}
        - uses: google-github-actions/release-please-action@v4
          id: release_please
          with:
            token:  ${{ steps.generate_token.outputs.token }}
            config-file: release-please-config.json
            manifest-file: .release-please-manifest.json




