name: Save Databricks Secret

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
        description : environment to save secret
      space:
          type: choice
          options:
            - feature
            - qa
            - synthetic
            - actual
            - release
          description: space
          required: true
      secret-name:
          type: string
          description: name of secret
          required: true
      secret-vaue:
          type: string
          description: value of secret
          required: true



jobs:
    save-databricks-secret:
      name: Save Databricks Secret
      uses: ./.github/workflows/resuable-save-databricks-secret.yml
      with:
        environment: ${inputs.environment}
        space: ${inputs.space}
        secret-name: ${inputs.secret-name}
        secret-value: ${inputs.secret-value}



